const fs = require("fs");
const path = require("path");
const { Client } = require("youtubei");
const ytdl = require("@distube/ytdl-core");

let youtubeClient = null;
function getYoutubeClient() {
  if (!youtubeClient) {
    youtubeClient = new Client();
  }
  return youtubeClient;
}

let ytdlAgent = null;
function getYtdlAgent() {
  if (!ytdlAgent) {
    ytdl.createAgent(
      [
        {
          domain: ".youtube.com",
          expirationDate: 1757251508.92396,
          hostOnly: false,
          httpOnly: false,
          name: "__Secure-1PAPISID",
          path: "/",
          sameSite: "unspecified",
          secure: true,
          session: false,
          storeId: "0",
          value: "jFwOYcbMxXG5f237/AMOC9e8thbYco0k_s",
          id: 1,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1757251508.924257,
          hostOnly: false,
          httpOnly: true,
          name: "__Secure-1PSID",
          path: "/",
          sameSite: "unspecified",
          secure: true,
          session: false,
          storeId: "0",
          value:
            "g.a000mgiazkuTfwJXY85PKf8xuUEmuruDpjSkOkPD3BvS8zrDQoXeugvA96yaqazAfE585-hddgACgYKAa0SARcSFQHGX2MikS4wbricw_iTO8UZnDIoJRoVAUF8yKryHEPRxJBpoDJf3VYEq2BB0076",
          id: 2,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1754804032.904943,
          hostOnly: false,
          httpOnly: true,
          name: "__Secure-1PSIDCC",
          path: "/",
          sameSite: "unspecified",
          secure: true,
          session: false,
          storeId: "0",
          value:
            "AKEyXzU2EbbDRK_b5uSkGyvepC-Kkm0IXAYPwp3ntkGlRUrlZHCR-TTp30wNfz30Rxqdd4ZoE8s",
          id: 3,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1754804001.902817,
          hostOnly: false,
          httpOnly: true,
          name: "__Secure-1PSIDTS",
          path: "/",
          sameSite: "unspecified",
          secure: true,
          session: false,
          storeId: "0",
          value:
            "sidts-CjIBUFGohzi1YnJ4_4FXcGxTZyxySxrK8VkypJ1vFXLJ1FzWzQPhsQVd2DwHGnqBNkjp3hAA",
          id: 4,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1757251508.924008,
          hostOnly: false,
          httpOnly: false,
          name: "__Secure-3PAPISID",
          path: "/",
          sameSite: "no_restriction",
          secure: true,
          session: false,
          storeId: "0",
          value: "jFwOYcbMxXG5f237/AMOC9e8thbYco0k_s",
          id: 5,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1757251508.924296,
          hostOnly: false,
          httpOnly: true,
          name: "__Secure-3PSID",
          path: "/",
          sameSite: "no_restriction",
          secure: true,
          session: false,
          storeId: "0",
          value:
            "g.a000mgiazkuTfwJXY85PKf8xuUEmuruDpjSkOkPD3BvS8zrDQoXeqRNFqLLYQkvRxkR43MFxPgACgYKAfwSARcSFQHGX2MiCIHhZExiqsm2rU_l8tZeRRoVAUF8yKoJo-hiVOfdbVeQPZN3kReQ0076",
          id: 6,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1754804032.904968,
          hostOnly: false,
          httpOnly: true,
          name: "__Secure-3PSIDCC",
          path: "/",
          sameSite: "no_restriction",
          secure: true,
          session: false,
          storeId: "0",
          value:
            "AKEyXzW_mlXqiIqx_ZNHzVkeAoSLiRilhQtatbYY1s7WAhwbDP5zJAtVXWUQiaCaF25nRZpeMw",
          id: 7,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1754804001.903017,
          hostOnly: false,
          httpOnly: true,
          name: "__Secure-3PSIDTS",
          path: "/",
          sameSite: "no_restriction",
          secure: true,
          session: false,
          storeId: "0",
          value:
            "sidts-CjIBUFGohzi1YnJ4_4FXcGxTZyxySxrK8VkypJ1vFXLJ1FzWzQPhsQVd2DwHGnqBNkjp3hAA",
          id: 8,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1757251508.923774,
          hostOnly: false,
          httpOnly: false,
          name: "APISID",
          path: "/",
          sameSite: "unspecified",
          secure: false,
          session: false,
          storeId: "0",
          value: "yebfgjD9NM915pg1/ACL6GSpbYeavhS3JV",
          id: 9,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1723268600,
          hostOnly: false,
          httpOnly: false,
          name: "CONSISTENCY",
          path: "/",
          sameSite: "unspecified",
          secure: true,
          session: false,
          storeId: "0",
          value:
            "AKreu9t5jfJIPCD7r56zTVku5Q9yOBGPcwTOHpDKVguwUWQr2JVRSRhAoVrfnLmqHx65zFJPG_v9bYt_7Fhx3MPeBczMzKBHI2R6dJx6x7jTmkC6npQOoDaHVgvOzJ_6lHQitVQ1oKY1Yo6iFgdFKOOm",
          id: 10,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1757251508.92358,
          hostOnly: false,
          httpOnly: true,
          name: "HSID",
          path: "/",
          sameSite: "unspecified",
          secure: false,
          session: false,
          storeId: "0",
          value: "ALD0p7UK0IgpFSf5Y",
          id: 11,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1744617869.359928,
          hostOnly: false,
          httpOnly: true,
          name: "LOGIN_INFO",
          path: "/",
          sameSite: "no_restriction",
          secure: true,
          session: false,
          storeId: "0",
          value:
            "AFmmF2swRAIgPvhy7HujwZcGYtvajncRFGau8uzmAxsu7pgbGlrO_UsCIE0us6kAGaDM7Lk5a5NQAaTISwAPSTJvHnRNA9nkX1dR:QUQ3MjNmeE1qUW5TUVFBTTJmc2ZxSWFFNlVIZ29tY01JbmRDQlBxaXdnLU9xcEJyV2d5V3A3TE5tX1Z3TXdQNy1IRXBBSXNjUURqYjVROWFDcWNMX1Uwb1dsdlYyLVltNGtnOTJQVndBVjdBNWlkOF93UzZfX0w0RlVyNnBHSDZfVTU5a0xTeHRFTTZMemZDWExsemplY3RmZkRKRVZBRVFB",
          id: 12,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1757828005.131155,
          hostOnly: false,
          httpOnly: false,
          name: "PREF",
          path: "/",
          sameSite: "unspecified",
          secure: true,
          session: false,
          storeId: "0",
          value: "f7=4100&f6=40000000&tz=Asia.Calcutta",
          id: 13,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1757251508.923893,
          hostOnly: false,
          httpOnly: false,
          name: "SAPISID",
          path: "/",
          sameSite: "unspecified",
          secure: true,
          session: false,
          storeId: "0",
          value: "jFwOYcbMxXG5f237/AMOC9e8thbYco0k_s",
          id: 14,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1757251508.924216,
          hostOnly: false,
          httpOnly: false,
          name: "SID",
          path: "/",
          sameSite: "unspecified",
          secure: false,
          session: false,
          storeId: "0",
          value:
            "g.a000mgiazkuTfwJXY85PKf8xuUEmuruDpjSkOkPD3BvS8zrDQoXeqk39pWrIOJnPXSYejIe_bQACgYKAcMSARcSFQHGX2Mi1n5SpcSPR8-WRTQU59vYmxoVAUF8yKpzLuwK7R1RzTxcL7LGLIjZ0076",
          id: 15,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1754804032.904903,
          hostOnly: false,
          httpOnly: false,
          name: "SIDCC",
          path: "/",
          sameSite: "unspecified",
          secure: false,
          session: false,
          storeId: "0",
          value:
            "AKEyXzW9M0bPqX7nV9UPrwcTxhTTQJmYs62E9IHZPLc0ksHvjEP1zLpHECMx3IevNl-H-ceOD5Q",
          id: 16,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1757251508.923687,
          hostOnly: false,
          httpOnly: true,
          name: "SSID",
          path: "/",
          sameSite: "unspecified",
          secure: true,
          session: false,
          storeId: "0",
          value: "ARsB5NrIvOCBJLCUq",
          id: 17,
        },
        {
          domain: ".youtube.com",
          expirationDate: 1725609869.360005,
          hostOnly: false,
          httpOnly: true,
          name: "VISITOR_PRIVACY_METADATA",
          path: "/",
          sameSite: "no_restriction",
          secure: true,
          session: false,
          storeId: "0",
          value: "CgJJThIEGgAgKw%3D%3D",
          id: 18,
        },
      ],
      {
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
          "Accept-Language": "en-US,en;q=0.9",
          Referer: "https://www.youtube.com/",
        },
      }
    );
  }
  return ytdlAgent;
}

module.exports = { getYoutubeClient, getYtdlAgent };
